

DROP DATABASE IF EXISTS ;
CREATE DATABASE IF NOT EXISTS Intercollegiate_Athletic;
USE Intercollegiate_Athletic;

CREATE TABLE CUSTOMER (
    CUSTNO 		varchar(10) 		NOT NULL,
    CUSTNAME 	varchar(50) 	NOT NULL,
    ADDRESS  	varchar(50) 	NOT NULL,
    INTERNAL 	varchar(4)  	NOT NULL,
    CONTACT  	varchar(50) 	NOT NULL,
    PHONE 		varchar(15) 	NOT NULL,
    CITY 		varchar(20) 	NOT NULL,
    STATE 		varchar(5) 		NOT NULL,
    ZIP 		varchar(10) 			NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY(CUSTNO)
);


CREATE TABLE EMPLOYEE (
	EMPNO 		varchar(10)		NOT NULL,
	EMPNAME 	varchar(50)		NOT NULL,
	DEPARTMENT	varchar(30)		NOT NULL,
	EMAIL		varchar(30)		NOT NULL,
	PHONE 		varchar(15)		NOT NULL,
	CONSTRAINT PK_EMPLOYEE PRIMARY KEY(EMPNO)
);

CREATE TABLE FACILITY (
	FACNO 		varchar(10)		NOT NULL,
	FACNAME 	varchar(50)		NOT NULL,
	CONSTRAINT PK_FACILITY PRIMARY KEY(FACNO)
);

CREATE TABLE RESOURCETBL (
	RESNO 		varchar(10)		NOT NULL,
	RESNAME 	varchar(50)		NOT NULL,
	RATE		DECIMAL(10,2) 			NOT NULL,
	CONSTRAINT PK_RESOURCETBL PRIMARY KEY(RESNO),
	CONSTRAINT CHECKING_RATE CHECK(RATE > 0)	
);

CREATE TABLE LOCATION (
	LOCNO 		varchar(10)		NOT NULL,
	FACNO 		varchar(10)		NOT NULL,
	LOCNAME 	varchar(50)		NOT NULL,
	CONSTRAINT PK_LOCATION PRIMARY KEY(LOCNO),
	CONSTRAINT FK_LOCATION_FACILITY FOREIGN KEY(FACNO) references FACILITY(FACNO) ON DELETE CASCADE
);


CREATE TABLE EVENTREQUEST (
	EVENTNO 	varchar(10)		NOT NULL,
	DATEHELD 	DATE 			NOT NULL,
	DATEREQ		DATE 			NOT NULL,
	FACNO 		varchar(10)		NOT NULL,
	CUSTNO 		varchar(10)		NOT NULL,
	DATEAUTH 	DATE,
	STATUS		varchar(10)		NOT NULL,
	ESTCOST 	DECIMAL(10,2) 	NOT NULL,
	ESTAUDIENCE DECIMAL(10)		NOT NULL,
	BUDNO		varchar(10),	
	CONSTRAINT PK_EVENTREQUEST PRIMARY KEY(EVENTNO),
	CONSTRAINT FK_EVENTREQUEST_FACILITY FOREIGN KEY(FACNO) references FACILITY(FACNO) ON DELETE CASCADE,
	CONSTRAINT FK_EVENTREQUEST_CUSTOMER FOREIGN KEY(CUSTNO) references CUSTOMER(CUSTNO) ON DELETE CASCADE,
	CONSTRAINT CHECKING_STATUS CHECK (STATUS IN ("Denied", "Approved", "Pending")),
	CONSTRAINT CHECKING_ESTCOST CHECK(ESTCOST > 0)
);


CREATE TABLE EVENTPLAN (
	PLANNO		varchar(10) 	NOT NULL,
	EVENTNO 	varchar(10)		NOT NULL,
	WORKDATE 	DATE 			NOT NULL,
	NOTES 		varchar(100),
	ACTIVITY 	varchar(30) 	NOT NULL,
	EMPNO 		varchar(10),
	CONSTRAINT PK_EVENTPLAN PRIMARY KEY(PLANNO),
	CONSTRAINT FK_EVENTPLAN_EVENTREQUEST FOREIGN KEY(EVENTNO) references EVENTREQUEST(EVENTNO) ON DELETE CASCADE,
	CONSTRAINT FK_EVENTPLAN_EMPLOYEE FOREIGN KEY(EMPNO) references EMPLOYEE(EMPNO) ON DELETE CASCADE
);

CREATE TABLE EVENTPLANLINE (
	PLANNO 		varchar(10) 	NOT NULL,
	LINENO 		INT 			NOT NULL,
	TIMESTART 	DATE 			NOT NULL,
	TIMEEND 	DATE 			NOT NULL,
	NUMBERFLD	INT 	 		NOT NULL,
	LOCNO 		varchar(10)   	NOT NULL,
	RESNO 		varchar(10)  	NOT NULL,
	CONSTRAINT PK_EVENTPLANLINE PRIMARY KEY(PLANNO, LINENO),
	CONSTRAINT FK_EVENTPLANLINE_EVENTPLAN FOREIGN KEY(PLANNO) references EVENTPLAN(PLANNO) ON DELETE CASCADE,
	CONSTRAINT FK_EVENTPLANLINE_LOCATION FOREIGN KEY(LOCNO) references LOCATION(LOCNO) ON DELETE CASCADE,
	CONSTRAINT FK_EVENTPLANLINE_RESOURCETBL FOREIGN KEY(RESNO) references RESOURCETBL(RESNO) ON DELETE CASCADE,
	CONSTRAINT CHECKING_TIME CHECK(TIMESTART > TIMEEND)
);